更新 Update_easylist.yml

diff --git a/.github/workflows/Update_easylist.yml b/.github/workflows/Update_easylist.yml
--- a/.github/workflows/Update_easylist.yml
+++ b/.github/workflows/Update_easylist.yml
@@ -6,30 +6,39 @@ on:
       - main
 
 jobs:
-  update_easylist:
+  update:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Download easylist.txt
-        run: curl -o easylist_1.txt https://easylist-downloads.adblockplus.org/easylist.txt
-
-      - name: Process and compare easylist.txt
+      - name: Download and process easylist.txt
         run: |
-          sed -i '/^.{1024,}/d' easylist_1.txt
-          if ! cmp -s easylist_1.txt ${{ github.workspace }}/easylist.txt; then
-            cp easylist_1.txt ${{ github.workspace }}/easylist.txt
-            echo "easylist.txt 文件已更新"
-            echo "* $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - easylist.txt 文件已更新" >> ${{ github.workspace }}/README.md
+         curl -o easylist_downloaded.txt https://easylist-downloads.adblockplus.org/easylist.txt
+         sed '/^.\{1024,\}/d' easylist_downloaded.txt > easylist_filtered.txt
+
+      - name: Compare files
+        id: compare
+        run: |
+          if ! cmp --silent easylist_filtered.txt ${{ github.workspace }}/easylist.txt; then
+           echo "Files are different. Updating easylist.txt"
+           mv easylist_filtered.txt ${{ github.workspace }}/easylist.txt
+           processed_lines=$(grep -c '^.\{1024,\}' easylist_downloaded.txt)
+           if [ -z "$processed_lines" ]; then
+             processed_lines=0
+           fi
+           echo "* $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - easylist.txt 文件已更新，处理了 $processed_lines 行" >> ${{ github.workspace }}/README.md
           else
-            echo "easylist.txt 文件一致"
-            echo "$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - easylist.txt 文件一致" >> ${{ github.workspace }}/log/log.txt
+           processed_lines=$(grep -c '^.\{1024,\}' easylist_downloaded.txt)
+           if [ -z "$processed_lines" ]; then
+              processed_lines=0
+           fi
+           echo "Files are the same. No action required."
+           echo "$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - easylist.txt 文件无更新，处理了 $processed_lines 行" >> ${{ github.workspace }}/log/log.txt
           fi
 
       - name: Clean up downloaded file
-        run: rm easylist_1.txt
+        run: rm easylist_downloaded.txt
 
       - name: Commit and push changes
         run: |
